services:

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo_data:/data/db

  goserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:50051"
    environment:
      TEST_ENV_Var: test
    depends_on:
      - mongodb
