// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pkg/employee.proto

package pkg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeOpsClient is the client API for EmployeeOps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeOpsClient interface {
	Add(ctx context.Context, in *AddEmployeeRequest, opts ...grpc.CallOption) (*AddEmployeeResponse, error)
}

type employeeOpsClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeOpsClient(cc grpc.ClientConnInterface) EmployeeOpsClient {
	return &employeeOpsClient{cc}
}

func (c *employeeOpsClient) Add(ctx context.Context, in *AddEmployeeRequest, opts ...grpc.CallOption) (*AddEmployeeResponse, error) {
	out := new(AddEmployeeResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeOps/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeOpsServer is the server API for EmployeeOps service.
// All implementations must embed UnimplementedEmployeeOpsServer
// for forward compatibility
type EmployeeOpsServer interface {
	Add(context.Context, *AddEmployeeRequest) (*AddEmployeeResponse, error)
	mustEmbedUnimplementedEmployeeOpsServer()
}

// UnimplementedEmployeeOpsServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeOpsServer struct {
}

func (UnimplementedEmployeeOpsServer) Add(context.Context, *AddEmployeeRequest) (*AddEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedEmployeeOpsServer) mustEmbedUnimplementedEmployeeOpsServer() {}

// UnsafeEmployeeOpsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeOpsServer will
// result in compilation errors.
type UnsafeEmployeeOpsServer interface {
	mustEmbedUnimplementedEmployeeOpsServer()
}

func RegisterEmployeeOpsServer(s grpc.ServiceRegistrar, srv EmployeeOpsServer) {
	s.RegisterService(&EmployeeOps_ServiceDesc, srv)
}

func _EmployeeOps_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeOpsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeOps/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeOpsServer).Add(ctx, req.(*AddEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeOps_ServiceDesc is the grpc.ServiceDesc for EmployeeOps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeOps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeOps",
	HandlerType: (*EmployeeOpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _EmployeeOps_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/employee.proto",
}
